export const COUNTRY_LIST = [
  {
    id: 1,
    name: "france",
    continent: "유럽",
    krName: "프랑스",
    imageUrl: "/flags/france.png",
  },
  {
    id: 2,
    name: "japan",
    continent: "아시아",
    krName: "일본",
    imageUrl: "/flags/japan.png",
  },
  {
    id: 3,
    name: "germany",
    continent: "유럽",
    krName: "독일",
    imageUrl: "/flags/germany.png",
  },
  {
    id: 4,
    name: "italy",
    continent: "유럽",
    krName: "이탈리아",
    imageUrl: "/flags/italy.png",
  },
  {
    id: 5,
    name: "spain",
    continent: "유럽",
    krName: "스페인",
    imageUrl: "/flags/spain.png",
  },
  {
    id: 6,
    name: "canada",
    continent: "북아메리카",
    krName: "캐나다",
    imageUrl: "/flags/canada.png",
  },
  {
    id: 7,
    name: "australia",
    continent: "오세아니아",
    krName: "호주",
    imageUrl: "/flags/australia.png",
  },
  {
    id: 8,
    name: "brazil",
    continent: "남아메리카",
    krName: "브라질",
    imageUrl: "/flags/brazil.png",
  },
  {
    id: 10,
    name: "china",
    continent: "아시아",
    krName: "중국",
    imageUrl: "/flags/china.png",
  },
  {
    id: 11,
    name: "thailand",
    continent: "아시아",
    krName: "태국",
    imageUrl: "/flags/thailand.png",
  },
];
